"""Auto-generated by zsiga (P1-5 spec → pytest pipeline).

Do not edit manually — this file is overwritten when zsiga detects it
is missing. Add target-specific fixtures in the project's normal
conftest.py instead.
"""
from __future__ import annotations

import shutil
import subprocess
from pathlib import Path

import pytest


@pytest.fixture
def tmp_repo(tmp_path):
    """Create a fresh git repo for testing.

    Yields the ``Path`` of the repo root. Repo has user.name/user.email
    pre-configured so commits work without an external ~/.gitconfig.
    """
    subprocess.run(
        ["git", "init", "-q"], cwd=tmp_path, check=True, capture_output=True,
    )
    subprocess.run(
        ["git", "config", "user.name", "zsiga"],
        cwd=tmp_path, check=True, capture_output=True,
    )
    subprocess.run(
        ["git", "config", "user.email", "zsiga@local"],
        cwd=tmp_path, check=True, capture_output=True,
    )
    yield tmp_path


@pytest.fixture
def mock_transport():
    """Tiny in-memory Transport mock.

    Records every ``run_shell`` call on ``.commands``; ``write_file``
    persists to disk under tmp_path-style absolute paths supplied by
    the caller; ``exists`` mirrors filesystem state.
    """

    class _MockTransport:
        def __init__(self):
            self.commands: list[tuple[str, dict]] = []
            self._files: dict[str, str] = {}

        def run_shell(self, cmd, **kwargs):
            self.commands.append((cmd, kwargs))
            return {"exit_code": 0, "stdout": "", "stderr": ""}

        def write_file(self, path: str, content: str):
            Path(path).parent.mkdir(parents=True, exist_ok=True)
            Path(path).write_text(content)
            self._files[path] = content

        def read_file(self, path: str) -> str | None:
            try:
                return Path(path).read_text()
            except FileNotFoundError:
                return None

        def exists(self, path: str) -> bool:
            return Path(path).exists()

    return _MockTransport()

