"""Validate and post-process pytest artifacts produced by ENRICH.

Phase 2 of the spec → pytest pipeline. The ENRICHER agent is asked (in
its system prompt) to generate two things for each testable scenario:

  1. A spec markdown block with ``- **testable**: true`` and
     ``- **target**: <file>::<symbol>``
  2. A pytest test file alongside in
     ``<target_path>/tests/test_spec_<change_id_slug>__<spec_slug>.py``
     containing a real ``def test_<scenario_slug>(): ...`` function

This module's job runs *after* the agent finishes:

- walk ``<change_dir>/specs/*.md``
- parse each spec via :mod:`zsiga.pipeline.spec_parser`
- for every scenario marked ``testable=True``:
    * compute the expected test file path
    * if file missing → demote the scenario to ``testable: false``
    * if file present but ``py_compile`` fails → delete the file and
      demote the scenario
- write a fresh ``conftest_zsiga.py`` if missing (one-shot, fixed template)
- return a :class:`SpecPytestReport` summarising what was validated /
  demoted, so the caller (enricher) can log a single concise line to the
  daemon log

Demotion mechanism: we rewrite the spec markdown by replacing the
``- **testable**: true`` line with
``- **testable**: false  <!-- demoted by zsiga: <reason> -->`` so REVIEW
can see the demotion and decide whether the scenario was misclassified.
"""
from __future__ import annotations

import os
import py_compile
import re
import tempfile
from dataclasses import dataclass, field

from ..transport import LocalTransport, Transport
from .spec_parser import Scenario, parse_spec
from .utils import list_files_recursive, read_file


# ---------------------------------------------------------------------------
# Path helpers
# ---------------------------------------------------------------------------


def _slugify(name: str) -> str:
    """Filename-safe slug: lower, alnum + underscore only."""
    s = re.sub(r"[^A-Za-z0-9]+", "_", name).strip("_").lower()
    return s or "x"


def expected_test_path(target_path: str, change_id: str, spec_filename: str) -> str:
    """Compute the test file path for a given spec.

    ``spec_filename`` is the basename of the spec markdown
    (e.g. ``phase-progress-bar.md``). ``change_id`` is the directory name
    of the change (e.g. ``dashboard-proposal-queue-mobile``).
    Returns absolute path under ``target_path/tests/``.
    """
    spec_slug = _slugify(spec_filename.removesuffix(".md"))
    change_slug = _slugify(change_id)
    fname = f"test_spec_{change_slug}__{spec_slug}.py"
    return os.path.join(target_path, "tests", fname)


# ---------------------------------------------------------------------------
# conftest_zsiga.py — fixed template, written once per target
# ---------------------------------------------------------------------------

CONFTEST_ZSIGA = '''"""Auto-generated by zsiga (P1-5 spec → pytest pipeline).

Do not edit manually — this file is overwritten when zsiga detects it
is missing. Add target-specific fixtures in the project\'s normal
conftest.py instead.
"""
from __future__ import annotations

import shutil
import subprocess
from pathlib import Path

import pytest


@pytest.fixture
def tmp_repo(tmp_path):
    """Create a fresh git repo for testing.

    Yields the ``Path`` of the repo root. Repo has user.name/user.email
    pre-configured so commits work without an external ~/.gitconfig.
    """
    subprocess.run(
        ["git", "init", "-q"], cwd=tmp_path, check=True, capture_output=True,
    )
    subprocess.run(
        ["git", "config", "user.name", "zsiga"],
        cwd=tmp_path, check=True, capture_output=True,
    )
    subprocess.run(
        ["git", "config", "user.email", "zsiga@local"],
        cwd=tmp_path, check=True, capture_output=True,
    )
    yield tmp_path


@pytest.fixture
def mock_transport():
    """Tiny in-memory Transport mock.

    Records every ``run_shell`` call on ``.commands``; ``write_file``
    persists to disk under tmp_path-style absolute paths supplied by
    the caller; ``exists`` mirrors filesystem state.
    """

    class _MockTransport:
        def __init__(self):
            self.commands: list[tuple[str, dict]] = []
            self._files: dict[str, str] = {}

        def run_shell(self, cmd, **kwargs):
            self.commands.append((cmd, kwargs))
            return {"exit_code": 0, "stdout": "", "stderr": ""}

        def write_file(self, path: str, content: str):
            Path(path).parent.mkdir(parents=True, exist_ok=True)
            Path(path).write_text(content)
            self._files[path] = content

        def read_file(self, path: str) -> str | None:
            try:
                return Path(path).read_text()
            except FileNotFoundError:
                return None

        def exists(self, path: str) -> bool:
            return Path(path).exists()

    return _MockTransport()


@pytest.fixture
def ruff_runner():
    """Run ruff against a working directory if the binary is installed.

    Returns a callable ``runner(args: list[str], cwd: str | Path)`` that
    invokes ``ruff <args>`` in ``cwd`` and returns
    ``(returncode, stdout, stderr)``. Tests requesting this fixture are
    automatically skipped via ``pytest.skip(...)`` when the ``ruff``
    binary is not on ``PATH``, so they remain green in environments
    that don't bundle ruff.

    Tests that only need to verify pipeline *behaviour* (e.g. "the
    pipeline tried to invoke ruff") should mock ``subprocess.run``
    directly instead of using this fixture; ``ruff_runner`` is for
    tests that actually need to assert on ruff's real output.
    """
    import shutil
    import subprocess

    ruff_path = shutil.which("ruff")
    if not ruff_path:
        pytest.skip("ruff binary not on PATH; skipping lint-dependent test")

    def _run(args, cwd):
        result = subprocess.run(
            [ruff_path] + list(args),
            cwd=str(cwd),
            capture_output=True,
            text=True,
            timeout=30,
        )
        return result.returncode, result.stdout, result.stderr

    return _run
'''


def ensure_conftest(target_path: str, transport: Transport | None = None) -> bool:
    """Write conftest_zsiga.py if it is missing.

    Returns True iff a new file was written.
    """
    transport = transport or LocalTransport()
    tests_dir = os.path.join(target_path, "tests")
    transport.run_shell(f"mkdir -p '{tests_dir}'", timeout=5)
    conf_path = os.path.join(tests_dir, "conftest_zsiga.py")
    existing = read_file(conf_path, transport)
    if existing is not None:
        return False
    transport.run_shell(
        f"cat > '{conf_path}' <<'ZSIGA_CONFTEST_EOF'\n{CONFTEST_ZSIGA}\nZSIGA_CONFTEST_EOF",
        timeout=10,
    )
    return True


# ---------------------------------------------------------------------------
# Validation
# ---------------------------------------------------------------------------


def _py_compile_ok(source_text: str) -> tuple[bool, str]:
    """Return (ok, error_message). Uses py_compile via a tmpfile."""
    with tempfile.NamedTemporaryFile(
        suffix=".py", mode="w", delete=False, encoding="utf-8",
    ) as f:
        f.write(source_text)
        tmp = f.name
    try:
        try:
            py_compile.compile(tmp, doraise=True)
            return True, ""
        except py_compile.PyCompileError as exc:  # pragma: no cover - defensive
            return False, str(exc)
    finally:
        try:
            os.unlink(tmp)
        except OSError:  # pragma: no cover
            pass


_TESTABLE_LINE_RE = re.compile(
    r"(?P<prefix>^[\s*\-]*\*\*testable\*\*\s*:?\s*)"
    r"(?P<value>true)"
    r"(?P<rest>.*)$",
    re.IGNORECASE | re.MULTILINE,
)


def _demote_in_spec(spec_text: str, scenario_name: str, reason: str) -> str:
    """Replace the *first* ``testable: true`` line under ``scenario_name``
    with ``testable: false  <!-- demoted by zsiga: <reason> -->``.

    Conservative: only mutates the testable line, leaves target / Given /
    When / Then untouched so REVIEW can read the original intent.
    """
    # Find the scenario block by its heading
    heading_re = re.compile(
        rf"^(#{{3,6}})\s*Scenario\s*:\s*{re.escape(scenario_name)}\s*$",
        re.MULTILINE,
    )
    m = heading_re.search(spec_text)
    if not m:
        return spec_text
    block_start = m.end()
    # Block ends at next scenario heading (any depth ≥ 3) or EOF
    next_h = re.compile(r"^#{3,6}\s*Scenario\s*:", re.MULTILINE)
    nm = next_h.search(spec_text, block_start)
    block_end = nm.start() if nm else len(spec_text)

    block = spec_text[block_start:block_end]
    new_block, n = _TESTABLE_LINE_RE.subn(
        rf"\g<prefix>false  <!-- demoted by zsiga: {reason} -->",
        block,
        count=1,
    )
    if n == 0:
        return spec_text
    return spec_text[:block_start] + new_block + spec_text[block_end:]


@dataclass
class SpecValidation:
    """Per-spec record."""

    spec_filename: str
    scenarios_total: int = 0
    scenarios_testable_declared: int = 0
    scenarios_testable_validated: int = 0
    scenarios_demoted: list[tuple[str, str]] = field(default_factory=list)
    """Each tuple is ``(scenario_name, reason)``."""
    test_file_path: str | None = None
    test_file_present: bool = False
    test_file_compile_ok: bool = False


@dataclass
class SpecPytestReport:
    change_id: str
    target_path: str
    conftest_written: bool = False
    spec_validations: list[SpecValidation] = field(default_factory=list)

    @property
    def total_testable_declared(self) -> int:
        return sum(v.scenarios_testable_declared for v in self.spec_validations)

    @property
    def total_testable_validated(self) -> int:
        return sum(v.scenarios_testable_validated for v in self.spec_validations)

    @property
    def total_demoted(self) -> int:
        return sum(len(v.scenarios_demoted) for v in self.spec_validations)

    def summary_line(self) -> str:
        return (
            f"spec→pytest: {self.total_testable_validated}/"
            f"{self.total_testable_declared} testable scenarios validated, "
            f"{self.total_demoted} demoted, "
            f"conftest={'written' if self.conftest_written else 'present'}"
        )


def validate_testable_artifacts(
    change_dir: str,
    target_path: str,
    transport: Transport | None = None,
    *,
    allow_inferred_contract: bool = False,
) -> SpecPytestReport:
    """Walk specs, validate companion pytest files, demote on failure.

    Side effects: rewrites individual spec markdown files when a
    scenario must be demoted, deletes broken pytest files, optionally
    writes a fresh conftest_zsiga.py.

    Phase 6 — when ``allow_inferred_contract`` is ``False`` (default),
    any scenario marked ``testable: true`` without a ``contract:`` block
    is demoted to Layer 2; this avoids the 29% L1-FAIL signature-
    mismatch failure mode observed when ENRICH guesses signatures from
    the When-clause text. Pass ``allow_inferred_contract=True`` to
    accept the legacy inferred-signature path.
    """
    transport = transport or LocalTransport()
    change_id = os.path.basename(os.path.normpath(change_dir))
    report = SpecPytestReport(change_id=change_id, target_path=target_path)

    specs_dir = os.path.join(change_dir, "specs")
    spec_files = list_files_recursive(specs_dir, "*.md", transport)
    if not spec_files:
        return report

    report.conftest_written = ensure_conftest(target_path, transport)

    for spec_path in spec_files:
        spec_filename = os.path.basename(spec_path)
        spec_text = read_file(spec_path, transport) or ""
        scenarios = parse_spec(spec_text)
        validation = SpecValidation(
            spec_filename=spec_filename,
            scenarios_total=len(scenarios),
        )

        testable = [s for s in scenarios if s.testable]
        validation.scenarios_testable_declared = len(testable)

        if not testable:
            report.spec_validations.append(validation)
            continue

        # Phase 6: demote testable scenarios that lack an explicit contract,
        # unless the project opted into the legacy inferred-signature path.
        if not allow_inferred_contract:
            no_contract = [s for s in testable if s.contract is None]
            if no_contract:
                updated_text = spec_text
                for sc in no_contract:
                    updated_text = _demote_in_spec(
                        updated_text, sc.name,
                        "missing contract field (Phase 6 strict mode)",
                    )
                    validation.scenarios_demoted.append(
                        (sc.name, "missing contract"),
                    )
                transport.run_shell(
                    f"cat > '{spec_path}' <<'ZSIGA_DEMOTE_EOF'\n"
                    f"{updated_text}\n"
                    f"ZSIGA_DEMOTE_EOF",
                    timeout=10,
                )
                spec_text = updated_text
                # Re-derive testable list now that some scenarios were demoted
                scenarios = parse_spec(spec_text)
                testable = [s for s in scenarios if s.testable]
                if not testable:
                    report.spec_validations.append(validation)
                    continue

        # Compute expected test file path
        test_path = expected_test_path(target_path, change_id, spec_filename)
        validation.test_file_path = test_path
        test_source = read_file(test_path, transport)

        if test_source is None:
            # ENRICHER didn't generate the file — demote ALL testable
            # scenarios in this spec.
            updated_text = spec_text
            for sc in testable:
                updated_text = _demote_in_spec(
                    updated_text, sc.name,
                    "test file missing after ENRICH",
                )
                validation.scenarios_demoted.append(
                    (sc.name, "test file missing"),
                )
            transport.run_shell(
                f"cat > '{spec_path}' <<'ZSIGA_DEMOTE_EOF'\n"
                f"{updated_text}\n"
                f"ZSIGA_DEMOTE_EOF",
                timeout=10,
            )
            report.spec_validations.append(validation)
            continue

        validation.test_file_present = True
        ok, err = _py_compile_ok(test_source)
        if not ok:
            # Syntax error — delete file and demote scenarios.
            transport.run_shell(f"rm -f '{test_path}'", timeout=5)
            updated_text = spec_text
            for sc in testable:
                updated_text = _demote_in_spec(
                    updated_text, sc.name,
                    f"test file py_compile failed: {err.splitlines()[0][:100]}",
                )
                validation.scenarios_demoted.append((sc.name, "compile failed"))
            transport.run_shell(
                f"cat > '{spec_path}' <<'ZSIGA_DEMOTE_EOF'\n"
                f"{updated_text}\n"
                f"ZSIGA_DEMOTE_EOF",
                timeout=10,
            )
            report.spec_validations.append(validation)
            continue

        validation.test_file_compile_ok = True
        validation.scenarios_testable_validated = len(testable)
        report.spec_validations.append(validation)

    return report
